  name: build and deploy spring-api
  on:
    workflow_dispatch:

  jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-20.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 8
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 8
        - name: build the app
          run: |
            mvn -B package --file pom.xml
        - name: List target directory for debugging
          run: ls -la target
        - name: build the docker image
          run: docker build -t gitaction-spring:v1 .
        - name: 'Docker Login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_ENDPOINT }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - name: Docker tag
          run: docker tag gitaction-spring:v1 ${{ secrets.ACR_ENDPOINT }}/gitaction-spring:v1
        - name: Docker push
          run: docker push ${{ secrets.ACR_ENDPOINT }}/gitaction-spring:v1
          


        

            
