# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rest-api77

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerregistry77.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8ecfb761a3ee4c3ca651bb3af1eaa0a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_08986d5f51384a559222315fdf2fbf0f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerregistry77.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ecfb761a3ee4c3ca651bb3af1eaa0a4 }}/rest-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rest-api77'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_07ed8d96f595473bbbb7876401999f6e }}
        images: 'containerregistry77.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ecfb761a3ee4c3ca651bb3af1eaa0a4 }}/rest-api:${{ github.sha }}'
